import { VS_CODE_COLORS as C, type CodeToken } from "@/components/sections/ScrollTypedCode";

/** Portfolio intro — same beats as the original hero terminal, styled as code */
export const HERO_PROFILE_TOKENS: CodeToken[] = [
    { text: "// shubham@portfolio:~$ whoami\n\n", className: C.comment },
    { text: "const", className: C.keyword },
    { text: " ", className: C.punct },
    { text: "profile", className: C.ident },
    { text: " = {\n", className: C.punct },
    { text: "  ", className: C.punct },
    { text: "role", className: C.prop },
    { text: ": ", className: C.punct },
    { text: '"Computer Science undergraduate"', className: C.string },
    { text: ",\n", className: C.punct },
    { text: "  ", className: C.punct },
    { text: "focus", className: C.prop },
    { text: ": ", className: C.punct },
    { text: '"end-to-end web applications"', className: C.string },
    { text: ",\n", className: C.punct },
    { text: "}\n\n", className: C.punct },
    { text: "// shubham@portfolio:~$ ./start.sh\n", className: C.comment },
    { text: "async", className: C.keyword },
    { text: " ", className: C.punct },
    { text: "function", className: C.keyword },
    { text: " ", className: C.punct },
    { text: "start", className: C.fn },
    { text: "() {\n", className: C.punct },
    { text: "  ", className: C.punct },
    { text: "return", className: C.keyword },
    { text: " ", className: C.punct },
    { text: '"Loading my world..."', className: C.string },
    { text: "\n", className: C.punct },
    { text: "}", className: C.punct },
];
